### ISSUE TITLE
Composer installation doesn't work

### ISSUE THREAD

**Issue by winternet-studio** [Weble/Zoom#1]
Package is not available on packagist.org...

Neither manual installation works - there is no autoload.php!!!

**Comment by Skullbock** [comment]
Hi @winternet-studio this library is just a proof of concept. 
It's still in development, that's why it's not on packagist and the readme is just a stub.

Feel free to fork it or PR an update, but we're not going to work on it soon, the project it was meant for is not yet ready to be integrated with zoom.

i'll add a note in the readme regarding this.
